### ISSUE TITLE
Nextcloud 25: publish release to app store

### ISSUE THREAD

**Issue by ksarink** [pulsejet/nextcloud-oidc-login#202]
It seems that the current state of the plugin is ready to be used in Nextcloud 25. Is it possible to publish a new release and upload it to the Nextcloud app store?

**Comment by pulsejet** [comment]
Beta is now available for Nextcloud 25. Since there's been some major refactor, we need to test this for a few weeks before making a stable release. Will close this issue after that.

**Comment by GuiPoM** [comment]
Hello @pulsejet !
Do you had any feedback since that new version was released as beta ? 
I would like to upgrade to Nextcloud 25 and this plugin is now the only remaining one still not released as a compatible version. 
I cannot switch to beta, this is my prod instance. I also do not want to take a risk if you think it is not yet ready.
Thanks !

**Comment by pulsejet** [comment]
~100 people seemed to have downloaded from the unstable channel and no reports. Pushed to stable channel :)

**Comment by GuiPoM** [comment]
> ~100 people seemed to have downloaded from the unstable channel and no reports. Pushed to stable channel :)

Thanks. I just performed the upgrade to 25.0.1 and of course oidc-login 2.4.0 and my oauth authentication is still working as expected. That's great ! 👍
