### ISSUE TITLE
Pair existing LDAP users

### ISSUE THREAD

**Issue by petrhoracekcz** [pulsejet/nextcloud-oidc-login#24]
I use NC18 and "LDAP user and group backend" application. Now I installed "OpenID Connect Login" and set it up with Keycloak. My thinkg is replace LDAP with OpenID.

But when I logged with OpenID, NC created new user in oc_users table. My username attribute is mail.

Exist any way to pair existing LDAP user (table oc_ldap_user_mapping) with OpenID user?

Thank you for reply.

**Comment by pulsejet** [comment]
There's no way to do this that I know of (other than manually updating the
database) because of the way the users are stored. If you can use LDAP and
OIDC together, you can use the LDAP proxy function, where the user
information is retrieved from LDAP upon successful authorization with OIDC.
Check the readme.
