### ISSUE TITLE
Home Directory Using External Storage

### ISSUE THREAD

**Issue by Queuecumber** [pulsejet/nextcloud-oidc-login#29]
I would prefer if the custom home directory could be done using external storage instead of using a link. 

My users have their own home directories that are accessible in numerous ways. If I use the default behavior of this app, the link method, it creates a folder structure under their home directory which is then used for nextcloud file storage, instead of just exposing the existing home directory contents. Then, if I delete a user, it deletes the entire contents of the linked home directory because nextcloud assumes it owns that folder.

This could all be avoided by using an external storage configured as the "Local" type, which I believe is how the LDAP app does it, mapping it to the users "/" (root) folder, since these folders are explicitly marked as external, even if I delete a user with external storage root, it wont delete their files.

I tried to read through the LDAP app to see how they are doing it with the goal of preparing a PR for this, but the code is extremely long and complex and I was unable to find the mechanism in code for creating an external storage. I'll keep reading but I was hoping you had some idea of where I can look.

**Comment by pulsejet** [comment]
Yeah, the symlinking is just a hack that I had to create to get it to work with an old deployment transitioning from LDAP to OIDC. Nextcloud doesn't really allow using separate home directories, so there is no generic fix for this. The LDAP app, as you said, is amazingly complex in its handling of custom home dirs (which is why I gave up on a similar endeavor).

Off the top of my head, one workaround for your scenario might be to just delete the symlink (and maybe create a dummy?) before Nextcloud deletes the folder, perhaps through a hook in this app.

**Comment by Queuecumber** [comment]
I actually spent more time on this yesterday and I'm close to a solution. Basically it's just a matter of getting the external storage service in the login controller and making sure there is an appropriate external storage set up. The main blocker is simply lack of documentation for any of nextcloud internals.

**Comment by pulsejet** [comment]
Great! I'd be wary of using nextcloud's internal APIs though, since we can't ensure they won't change everyday.

**Comment by Queuecumber** [comment]
Is this considered an internal API? I thought the app APIs were free to be used and it's referenced from at least the LDAP app. 

At any rate I actually have it working now in a very rudimentary way so I'm going to polish it and prepare a PR

**Comment by Queuecumber** [comment]
@pulsejet I finished the PR for this, please take a look at your convenience
